version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
    reviewers:
      - "quortex/developers"
    rebase-strategy: "disabled"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
    reviewers:
      - "quortex/developers"
    rebase-strategy: "disabled"