steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/quortex-registry-public/prometheus/sleeker:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/quortex-registry-public/prometheus/sleeker:latest']
